apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asset-service
  namespace: argocd
spec:
  project: default

  sources:
    # 1️⃣ Helm chart from ACR
    - repoURL: oci://devacr301225.azurecr.io/helm
      chart: service
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/helm/values.yaml

    # 2️⃣ Values from Git repo
    - repoURL: https://github.com/ITAssetManagementSystem/AssetService.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: it-asset

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
