name: CI - PR Validation

on:
  pull_request:

  workflow_dispatch:

jobs:
  ci:
    uses: ITAssetManagementSystem/CommonWorkflows/.github/workflows/ci-helm-aks.yml@main
    with:
      service_name: asset-service
      dockerfile_path: Dockerfile
      chart_path: asset-service
      values_file: asset-service/values.yaml
